### ISSUE TITLE
DYS Family History Data Analysis

### ISSUE THREAD

**Issue by mosaa** [Research-Informatics-Lab/DYS_MUPC#1]

**Comment by mosaa** [comment]
@bac6d9: Do you have any plan for publishing this manuscript?

**Comment by bac6d9** [comment]
No, I am not. I have decided that I do not have time with step studying and other responsibilities.


From: Abu Saleh Mohammad Mosa ***@***.***>
Date: Thursday, February 3, 2022 at 9:47 AM
To: Research-Informatics-Lab/DYS_MUPC ***@***.***>
Cc: Calkins, Brittany (MU-Student) ***@***.***>, Mention ***@***.***>
Subject: Re: [Research-Informatics-Lab/DYS_MUPC] DYS Family History Data Analysis (#1)
WARNING: This message has originated from an External Source. This may be a phishing expedition that can result in unauthorized access to our IT System. Please use proper judgment and caution when opening attachments, clicking links, or responding to this email.

@bac6d9<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbac6d9&data=04%7C01%7Cbac6d9%40health.missouri.edu%7Cd381c23a796744be6e3608d9e72c6a70%7Ce3fefdbef7e9401ba51a355e01b05a89%7C0%7C0%7C637795000222038707%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3wptbzAEutQQQJzeu2Awl2dmNncgrgdq9SoQj3NjN5w%3D&reserved=0>: Do you have any plan for publishing this manuscript?

—
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FResearch-Informatics-Lab%2FDYS_MUPC%2Fissues%2F1%23issuecomment-1029125511&data=04%7C01%7Cbac6d9%40health.missouri.edu%7Cd381c23a796744be6e3608d9e72c6a70%7Ce3fefdbef7e9401ba51a355e01b05a89%7C0%7C0%7C637795000222038707%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Z4dr5caAVM%2BNv4nB%2BOW0HBzcHkoI2Lu3Ga%2BIy41KXik%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAU6OWSWOMAJOLWK62OV2ZFTUZKPPHANCNFSM5BGXBQLA&data=04%7C01%7Cbac6d9%40health.missouri.edu%7Cd381c23a796744be6e3608d9e72c6a70%7Ce3fefdbef7e9401ba51a355e01b05a89%7C0%7C0%7C637795000222194948%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=sO3U7Jg%2BiaZtg5LBFh9R0cp0QrtchNTus6X0stoblk0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cbac6d9%40health.missouri.edu%7Cd381c23a796744be6e3608d9e72c6a70%7Ce3fefdbef7e9401ba51a355e01b05a89%7C0%7C0%7C637795000222194948%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FLs2oIdmIyPdUFl1QKXueWk0aIyfngunl3aAJ6Qelic%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cbac6d9%40health.missouri.edu%7Cd381c23a796744be6e3608d9e72c6a70%7Ce3fefdbef7e9401ba51a355e01b05a89%7C0%7C0%7C637795000222194948%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=v%2BmpHPZnA1DJo45jF1Uz1x0pagaGCajtxtR4%2BA14g5w%3D&reserved=0>.

**Comment by mosaa** [comment]
@bac6d9: Thanks for the update.

**Comment by mosaa** [comment]
@bac6d9: Can you send us an APA style reference for the poster abstract that you presented?
